# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: Dee
title-normal: DeeHarding.Nu
email: dee@deeharding.nu
description: I'm a researcher at Goldsmiths College working at the boundary between science and art.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://heavyweather.github.io/" # the base hostname & protocol for your site
author:
street_address: Computing Department, Goldsmiths College
city: New Cross
state: London
zip_code: SE14 6NW
country: United(ish) Kingdom
phone: +44 (0)20 7919 7850

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
#  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 24

# Social settings
500px_url:
facebook_url: https://www.facebook.com/umbriel
github_url: https://www.github.com/heavyweather
gitlab_url:
googleplus_url: https://plus.google.com/u/0/+DeeHarding
instagram_url: https://instagram.com/dee.harding
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/deltaechoecho

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: deltaechoecho
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
